<<<<<<< HEAD
export { default as image1 } from "./1.png";
export { default as image2 } from "./2.png";
export { default as image3 } from "./3.png";
export { default as image4 } from "./4.png";
export { default as image5 } from "./5.png";
export { default as image6 } from "./6.png";
export { default as image7 } from "./7.png";
export { default as image8 } from "./8.png";
export { default as image9 } from "./9.png";
export { default as image10 } from "./10.png";
export { default as image11 } from "./11.png";
export { default as image12 } from "./12.png";
export { default as image13 } from "./13.png";
export { default as image14 } from "./14.png";
export { default as image15 } from "./15.png";
export { default as image16 } from "./16.png";
export { default as image17 } from "./17.png";
export { default as image18 } from "./18.png";
export { default as image19 } from "./19.png";
export { default as image20 } from "./20.png";
export { default as image21 } from "./21.png";
export { default as image22 } from "./22.png";
export { default as image23 } from "./23.png";
export { default as logo } from "./logo.png";
export { default as logonb } from "./logonb.png";
export { default as logowb } from "./logonwb.png";
=======
export { default as image1 } from "./1-min.png"
export { default as image2 } from "./2-min.png"
export { default as image3 } from "./3-min.png"
export { default as image4 } from "./4-min.png"
export { default as image5 } from "./5-min.png"
export { default as image6 } from "./6-min.png"
export { default as image7 } from "./7-min.png"
export { default as image8 } from "./8-min.png"
export { default as image9 } from "./9-min.png"
export { default as image10 } from "./10-min.png"
export { default as image11 } from "./11-min.png"
export { default as image12 } from "./12-min.png"
export { default as image13 } from "./13-min.png"
export { default as image14 } from "./14-min.png"
export { default as image15 } from "./15-min.png"
export { default as image16 } from "./16-min.png"
export { default as image17 } from "./17-min.png"
export { default as image18 } from "./18-min.png"
export { default as image19 } from "./19-min.png"
export { default as image20 } from "./20-min.png"
export { default as image21 } from "./21-min.png"
export { default as image22 } from "./22-min.png"
export { default as image23 } from "./23-min.png"
>>>>>>> eb608c32bbbc0cec3722e95b5bd7f57c30904c51
